// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:3d63208f-ab90-4e4b-a8d2-33fe37fe4e06",
    "aws_cognito_region": "us-east-2",
    "oauth": {},
    "aws_mobile_analytics_app_id": "87b3c486791a4fccae9f7d39591d8d56",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
